In [1]:
1+2

3

In [2]:
a=10

In [3]:
int a=10

SyntaxError: invalid syntax (<ipython-input-3-94a2776b5eb5>, line 1)

In [4]:
name="john"
salary=200023.234

In [6]:
a=10
b=10
c=10
a=b=c=10
x=20
y=30
z=40
x,y,z=20,30,40
print(y,a)


30 10


In [7]:
at@123=10

SyntaxError: can't assign to operator (<ipython-input-7-408841571be3>, line 1)

In [8]:
at.we=20

NameError: name 'at' is not defined

In [9]:
at_we=20

In [11]:
a=20
A=10
print(a)
print(A)

20
10


In [12]:
12at=10

SyntaxError: invalid syntax (<ipython-input-12-1e936a0f05ea>, line 1)

In [13]:
_12at=10

In [14]:
name1="john"
name2='james'

In [15]:
multiline='''str1
str2
str3
'''
print(multiline)

str1
str2
str3



In [21]:
#to print multiplelines 
multiline1='''str1 
str2
str3
str4
str5
'''
print(multiline1)

str1
str2
str3
str4
str5



In [23]:
var=10 #logical operator
var+=10 #var=var+10
print(var)
var-=10
print(var)

20
10


In [25]:
a=10<10 and 2>-1 #false and true=false
print(a)

False


In [26]:
10>>2 #bitwise operator

2

In [27]:
10<<2

40

In [28]:
#finding datatype of variables
a=10
name="jill"
salary=2000.23
print(type(a))
print(type(name))
print(type(salary))

<class 'int'>
<class 'str'>
<class 'float'>


In [29]:
str1="helloworld"
str2="intelligent"
print(str1[0])
print(str2[-1])

h
t


In [30]:
#Extract hello from helloworld
print(str1[0:5])

hello


In [31]:
#finding position of the string
str="Attachment"
str.find("me")

6

In [32]:
str.replace("me","m")

'Attachmnt'

In [33]:
str.replace("ment","")

'Attach'

In [34]:
splitstr="word1,word2,word3"
splitstr.split(",")

['word1', 'word2', 'word3']

In [35]:
str3="intelligent"
str3.count("i")

2

In [36]:
str3.upper()

'INTELLIGENT'

In [38]:
str4=str3.upper()

In [39]:
str4.count("I")

2

str5="!@#123AbacC"
max(str5)

In [41]:
min(str5)

'!'

In [42]:
#concatenation
mytuple=('a','b','c','d')
mytuple1=('e','f')
mytuple+=mytuple1
print(mytuple)

('a', 'b', 'c', 'd', 'e', 'f')


In [43]:
#repetation
mytuple*2

('a', 'b', 'c', 'd', 'e', 'f', 'a', 'b', 'c', 'd', 'e', 'f')

In [44]:
#indexing
mytuple[1]

'b'

In [ ]:
#slicing
mytuple[1:5]

In [47]:
#lists mutable datatypes
mylist=['a',123,3.14,'john']
mylist2=["python",20]
mylist+=mylist2
print(mylist)



['a', 123, 3.14, 'john', 'python', 20]


In [48]:
mylist.append("10")
print(mylist)

['a', 123, 3.14, 'john', 'python', 20, '10']


In [52]:
mylist3=['c','d']
mylist.append(mylist3)
print(mylist)

['a', 123, 3.14, 'john', 'python', 20, '10', ['c', 'd'], 'mylist3', ['c', 'd'], ['c', 'd']]


In [54]:
mylist.remove('mylist3')

In [55]:
print(mylist)

['a', 123, 3.14, 'john', 'python', 20, '10', ['c', 'd'], ['c', 'd'], ['c', 'd']]


In [57]:
mylist.remove(['c','d'])

In [58]:
print(mylist)

['a', 123, 3.14, 'john', 'python', 20, '10', ['c', 'd'], ['c', 'd']]


In [59]:
mylist.remove(['c','d'])

In [60]:
print(mylist)

['a', 123, 3.14, 'john', 'python', 20, '10', ['c', 'd']]


In [61]:
mylist.insert(1,30)
print(mylist)

['a', 30, 123, 3.14, 'john', 'python', 20, '10', ['c', 'd']]


In [62]:
test1='PythonProgramming'
print(test1[2:6])

thon


In [3]:
a=10
while a>0:
    a-=1
    if(a!=5):
        print(a)
    else:
        break
            

9
8
7
6


In [4]:
a=10
while a>0:
    a-=1
    if(a!=5):
        print(a)
    else:
        continue

9
8
7
6
4
3
2
1
0


In [5]:
def add(a,b):
    sum=a+b
    return sum

In [7]:
a=10
def myfunc(b):
    print("the value of b is",b)
    b=100
    print("the new value of b is",b)
    #calling a function by passing a value to it:
myfunc(a)

the value of b is 10
the new value of b is 100


In [9]:
#calling a function by reference
c=[10,20,30]
def myfunc2(d):
    print("the value of d is",d)
    d[0]=99
    d[1]=98
    print("the new value of d is",d)
myfunc2(c)

the value of d is [10, 20, 30]
the new value of d is [99, 98, 30]


In [17]:
def my_function(fname,lname):
    print("..........")

In [19]:
a=20
def my_function1(x):
    x+=10
    print(x)
my_function1(a)
    

30


In [20]:
#lambda function
x=lambda a:a+10
print(x(5))

15


In [21]:
def multi(x,y):
    return x*y

In [23]:
z=lambda x,y:x*y
print(z(12,5))

60


In [24]:
def myfunc(n):
    return lambda a:a*n

In [25]:
doubleme=myfunc(2)
print(doubleme(12))

24


In [26]:
d=lambda a,b,c:a+b+c
print(d(1,2,3))

6


In [27]:
def myfunc4(n):
    return lambda a:a*n
mydoubler=myfunc4(2)
print(mydoubler(11))

22


In [28]:
f=open("D:/testfile",'x')

In [29]:
f=open("D:/testfile1.txt","r")
print(f.read())

Hello Everyone
Welcome To Python
Goodluck


In [30]:
f=open("D:/testfile1.txt","r")
print(f.read(5))#print first 5 charecters fro the text file

Hello


In [31]:
f=open("D:/testfile1.txt","r")
print(f.readline())

Hello Everyone



In [32]:
f=open("D:/testfile1.txt","r")
print(f.readline())
print(f.readline())


Hello Everyone

Welcome To Python



In [33]:
f=open("D:/testfile1.txt","r")
for x in f:
    print(x)

Hello Everyone

Welcome To Python

Goodluck


In [35]:
f=open("D:/testfile1.txt","a")
print(f.write("This is the appending statement"))


31


In [36]:
f=open("D:/testfile1.txt","r")
for x in f:
    print(x)

Hello Everyone

Welcome To Python

GoodluckThis is the appending statement


In [37]:
f=open("D:/testfile1.txt","w")#overwrite my statements
print(f.write("this will overwirte everything"))


30


In [38]:
f=open("D:/testfile1.txt","r")
for x in f:
    print(x)

this will overwirte everything


In [39]:
f=open("D:/testfile1.txt","x")

FileExistsError: [Errno 17] File exists: 'D:/testfile1.txt'

In [40]:
f.close()

In [41]:
import os
os.remove("D:/testfile1.txt")

In [43]:
#NUMPY
import numpy as np
a=np.array([1,2,3])#LIST
b=np.array((1,2,3))#TUPLE
print(a)
print(b)

[1 2 3]
[1 2 3]


In [44]:
b[1]=4

In [45]:
b

array([1, 4, 3])

In [47]:
print(b)

[1 4 3]


In [71]:
import numpy as np
d=np.array([[1,2,3],[4,5,6]])
print(d)

[[1 2 3]
 [4 5 6]]


In [72]:
print(d[0])

[1 2 3]


In [73]:
print(d[1])

[4 5 6]


In [74]:
print(d[:0])

[]


In [75]:
print(d[0:])

[[1 2 3]
 [4 5 6]]


In [77]:
print(d[1:])

[[4 5 6]]


In [80]:
d[:1]

array([[1, 2, 3]])

In [81]:
a[0]

array([1, 2, 3])