In [1]:
#NUMPY
import numpy as np
a=np.array([1,2,3])#LIST
b=np.array((1,2,3))#TUPLE
print(a)
print(b)

[1 2 3]
[1 2 3]


In [2]:
b[1]=4

In [3]:
b

array([1, 4, 3])

In [4]:
import numpy as np
c=np.array([[1,2,3],[4,5,6]])
print(c)

[[1 2 3]
 [4 5 6]]


In [5]:
print(c[0])

[1 2 3]


In [6]:
print(c[1])

[4 5 6]


In [7]:
print(c[:0])

[]


In [8]:
print(c[0:])

[[1 2 3]
 [4 5 6]]


In [9]:
c[:1]

array([[1, 2, 3]])

In [10]:
print(c[1:])

[[4 5 6]]


In [11]:
c[:1]

array([[1, 2, 3]])

In [12]:
a[0]

1

In [13]:
a[1]

2

In [14]:
a[2]

3

In [16]:
a[1:2]

array([2])

In [17]:
a[1:3]

array([2, 3])

In [18]:
a[1:]

array([2, 3])

In [19]:
type(a)

numpy.ndarray

In [20]:
print(a)

[1 2 3]


In [21]:
a=np.zeros((3,4))
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [22]:
#creating the intervals
a=np.arange(10,25,5)#(starting,ending,interval)
print(a)

[10 15 20]


In [23]:
#creating points over straight line
#np.linspace(starting,ending,numberofpoints)
b=np.linspace(5,6,10)
print(b)


[5.         5.11111111 5.22222222 5.33333333 5.44444444 5.55555556
 5.66666667 5.77777778 5.88888889 6.        ]


In [24]:
import numpy as np
#np.full((rownum,colnum),numbertofill)
c=np.full((3,4),5)
print(c)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [27]:
import numpy as np
d=np.random.random((3,4))
print(d)

[[0.73240876 0.95081659 0.98936315 0.40359449]
 [0.98098001 0.83980966 0.16061529 0.74701568]
 [0.90628087 0.70986718 0.95247132 0.84130925]]


In [28]:
a=np.array([[1,2,3],[4,5,6]])

In [29]:
print(a)
#a.shape returns tuple(rownum.colnum)
print(a.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [31]:
a.shape=(3,2)#we can also change the shape
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [32]:
a.shape=(3,2)
print(a.shape[0])#it will give number of rows
print(a)

3
[[1 2]
 [3 4]
 [5 6]]


In [33]:
a.shape=(3,2)
print(a.shape[1])#it will give number of columns
print(a)

2
[[1 2]
 [3 4]
 [5 6]]


In [34]:
#np.arange(number of points needed)
#will place the numbers between 0 till that number
a=np.arange(24)

In [35]:
a.size

24

In [36]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [39]:
a=np.array([[1,2,3],[4,5,6]])

In [40]:
a.shape=(3,2)
print(a.shape[0])
print(a.shape[1])
print(a.ndim)#returns dimension of an array
print(a)

3
2
2
[[1 2]
 [3 4]
 [5 6]]


In [41]:
a.dtype

dtype('int32')

In [42]:
b=np.linspace(5,6,9)
print(b)
print(b.dtype)

[5.    5.125 5.25  5.375 5.5   5.625 5.75  5.875 6.   ]
float64


In [47]:
#using numpy in mathematics
a=np.array([5,10])
np.sum(a)

15

In [55]:
b=np.array([2,3])
print(np.sum(a))
print(np.sum(b))
print(np.subtract((a,b))#doubt

15
5
[3 7]


In [53]:
print(np.sum([a,b]))

20


In [56]:
print(a)
print(b)

[ 5 10]
[2 3]


In [58]:
print(np.sum([a,b],axis=0))#column wise addition

[ 7 13]


In [59]:
print(np.sum([a,b],axis=1))#row wise addition

[15  5]


In [60]:
print(np.divide(a,b))

[2.5        3.33333333]


In [61]:
print(np.multiply(a,b))

[10 30]


In [62]:
print(np.log(a))

[1.60943791 2.30258509]


In [63]:
print(np.cos(a))

[ 0.28366219 -0.83907153]


In [64]:
print(np.sin(a))

[-0.95892427 -0.54402111]


In [70]:
a=np.array([1,2,3])
b=np.array([3,2,3])
print(np.equal(a,b))
print(np.array_equal(a,b))

[False  True  True]
False


In [72]:
a=np.array([1,2,3])
print(np.sum(a))
print(np.min(a))
print(np.max(a))
print(np.mean(a))
print(np.std(a))
print(np.median(a))
print(np.corrcoef(a))

6
1
3
2.0
0.816496580927726
2.0
1.0


In [73]:
a=np.array([[1,2,3],[4,5,6]])
print(np.sum(a))
print(np.min(a))
print(np.max(a))
print(np.mean(a))
print(np.std(a))
print(np.median(a))
print(np.corrcoef(a))

21
1
6
3.5
1.707825127659933
3.5
[[1. 1.]
 [1. 1.]]


In [75]:
#Broadcasting
a=np.array([[1,2,3],[4,5,6]])
b=np.array([3,4,5])
print(a)
print(b)
print(np.sum([a,b]))

[[1 2 3]
 [4 5 6]]
[3 4 5]
[[ 4  6  8]
 [ 7  9 11]]


In [76]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([3,4,5])
print(a)
print(b)
print(np.subtract(a,b))

[[1 2 3]
 [4 5 6]]
[3 4 5]
[[-2 -2 -2]
 [ 1  1  1]]


In [79]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a[0:])

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [81]:
print(a[:1,:])

[[1 2 3]]


In [82]:
print(a[:2,:])

[[1 2 3]
 [4 5 6]]


In [83]:
print(a[:3,:])

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [84]:
print(a[:,:1])

[[1]
 [4]
 [7]]


In [85]:
print(a[:,:2])

[[1 2]
 [4 5]
 [7 8]]


In [86]:
print(a[:,:3])

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [87]:
print(a[:,2:])

[[3]
 [6]
 [9]]


In [88]:
print(a[:,0:])

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [89]:
print(a[:,1:])

[[2 3]
 [5 6]
 [8 9]]


In [91]:
print(a[2:,:])

[[7 8 9]]


In [92]:
print(a[3:,:])

[]


In [93]:
print(a[1:,:])

[[4 5 6]
 [7 8 9]]


In [95]:
print(a[2:,:3])

[[7 8 9]]


In [96]:
#ARRAY MANIPULATION
a=np.array([1,2,3])
b=np.array([3,4,5])
print(np.concatenate([a,b],axis=0))

[1 2 3 3 4 5]


In [101]:
a=np.array([[1,2,3],[4,5,6]])
print(a)
b=np.array([[3,4,5],[5,6,7]])
print(b)
print(np.concatenate([a,b],axis=0))#doubt
print(np.concatenate([a,b],axis=1))#doubt

[[1 2 3]
 [4 5 6]]
[[3 4 5]
 [5 6 7]]
[[1 2 3]
 [4 5 6]
 [3 4 5]
 [5 6 7]]
[[1 2 3 3 4 5]
 [4 5 6 5 6 7]]


In [103]:
print(np.stack((a,b),axis=0))

[[[1 2 3]
  [4 5 6]]

 [[3 4 5]
  [5 6 7]]]


In [104]:
print(np.stack((a,b),axis=1))

[[[1 2 3]
  [3 4 5]]

 [[4 5 6]
  [5 6 7]]]


In [105]:
a=np.array([1,2,3])
print(a)
b=np.array([3,4,5])
print(b)
#print(np.concatenate([a,b],axis=0))
#print(np.concatenate([a,b],axis=1))

[1 2 3]
[3 4 5]


In [106]:
print(np.stack((a,b),axis=0))

[[1 2 3]
 [3 4 5]]


In [107]:
print(np.stack((a,b),axis=1))

[[1 3]
 [2 4]
 [3 5]]


In [108]:
a=np.array([[1,2,3],[4,5,6]])
print(a)
b=np.array([[3,4,5],[5,6,7]])
print(b)

[[1 2 3]
 [4 5 6]]
[[3 4 5]
 [5 6 7]]


In [109]:
print(np.stack((a,b),axis=0))

[[[1 2 3]
  [4 5 6]]

 [[3 4 5]
  [5 6 7]]]


In [110]:
print(np.stack((a,b),axis=1))

[[[1 2 3]
  [3 4 5]]

 [[4 5 6]
  [5 6 7]]]


In [111]:
a=np.array([1,2,3])
print(a)
b=np.array([3,4,5])
print(b)
#print(np.concatenate([a,b],axis=0))
#print(np.concatenate([a,b],axis=1))

[1 2 3]
[3 4 5]


In [112]:
print(np.stack((a,b),axis=0))

[[1 2 3]
 [3 4 5]]


In [113]:
print(np.stack((a,b),axis=1))

[[1 3]
 [2 4]
 [3 5]]


In [116]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[2,3,4],[5,6,7]])
print("MATRIX A")
print(a)
print("MATRIX B")
print(b)
print("Horizontal Stack....")
print(np.hstack((a,b)))
print("Horizontal concat....")
print(np.concatenate((a,b),axis=0))
print("Vertical Stack....")
print(np.vstack((a,b)))
print("Vertical concat....")
print(np.concatenate((a,b),axis=1))
print("Column Stack....")
print(np.column_stack((a,b)))

MATRIX A
[[1 2 3]
 [4 5 6]]
MATRIX B
[[2 3 4]
 [5 6 7]]
Horizontal Stack....
[[1 2 3 2 3 4]
 [4 5 6 5 6 7]]
Horizontal concat....
[[1 2 3]
 [4 5 6]
 [2 3 4]
 [5 6 7]]
Vertical Stack....
[[1 2 3]
 [4 5 6]
 [2 3 4]
 [5 6 7]]
Vertical concat....
[[1 2 3 2 3 4]
 [4 5 6 5 6 7]]
Column Stack....
[[1 2 3 2 3 4]
 [4 5 6 5 6 7]]


In [117]:
#SPLITING OF ARRAYS
#np.split(array,index,axis)
#array=>numpy array
#index=>int/list



In [118]:
print(a)

[[1 2 3]
 [4 5 6]]


In [119]:
print(np.split(a,2,0))

[array([[1, 2, 3]]), array([[4, 5, 6]])]


In [120]:
print(np.split(a,3,1))

[array([[1],
       [4]]), array([[2],
       [5]]), array([[3],
       [6]])]


In [121]:
print(np.split(a,[1,2],axis=0))

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([], shape=(0, 3), dtype=int32)]


In [122]:
print(np.split(a,[1,2],axis=1))

[array([[1],
       [4]]), array([[2],
       [5]]), array([[3],
       [6]])]


In [123]:
a[:,:1]

array([[1],
       [4]])

In [124]:
a[:,1:2]

array([[2],
       [5]])

In [126]:
a[:,2:]

array([[3],
       [6]])

In [143]:
#NUMPY VS LIST:MEMORY SIZE
import numpy as np
import sys
#define a list
l=range(1000)
print(l)
print("size of a list",sys.getsizeof(1)*len(l))#doubt
#define a numpy array
a=np.arange(1000)
print("size of an array",a.size*a.itemsize)#a.size=>length of array,a.itemsize=>size of the array stored in memory

range(0, 1000)
size of a list 28000
size of an array 4000


In [142]:
#NUMPY VS LIST:SPEED #DOUBT
import time
def using_List():
    t1=time.time()#starting/initial time
    X=range(100000)
    Y=range(100000)
    z=[X[i]+Y[i] for i in range(len(X))]
    return time.time()-t1

def using_Numpy():
    t1=time.time()
    a=np.arange(100000)
    b=np.arange(100000)
    z=a+b
    return time.time()-t1
list_time=using_List()
numpy_time=using_Numpy()
print(list_time,numpy_time)
print("In this example Numpy is"+str(list_time/numpy_time)+"times faster than a list")
    

0.06510758399963379 0.003999948501586914
In this example Numpy is16.277105561184957times faster than a list
